[package]
name = "project39-ar"
version = "0.1.0"
authors = ["Fun Maker <funmaker95@gmail.com>"]
edition = "2018"

[dependencies]
vulkano = { git = "https://github.com/funmaker/vulkano", rev = "ea5b0b833e95d7b2e039c60faa34db4ab7b84440" }
vulkano-shaders = { git = "https://github.com/funmaker/vulkano", rev = "ea5b0b833e95d7b2e039c60faa34db4ab7b84440" }
vulkano-win = { git = "https://github.com/funmaker/vulkano", rev = "ea5b0b833e95d7b2e039c60faa34db4ab7b84440" }
#vulkano = { path = "../vulkano/vulkano" }
#vulkano-shaders = { path = "../vulkano/vulkano-shaders" }
#vulkano-win = { path = "../vulkano/vulkano-win" }
#vulkano = "0.23.0"
#vulkano-shaders = "0.23.0"
#vulkano-win = "0.23.0"
image = "0.23.12"
openvr = "0.6.0"
openvr_sys = "2.0.3"
err-derive = "0.3.0"
getopts = "0.2.21"
arc-swap = "1.2.0"
obj-rs = "0.6.2"
opencv = { version = "0.47.0", features = ["buildtime-bindgen"] }
num-traits = "0.2.14"
num-derive = "0.3.3"
lazy_static = "1.4.0"
winit = "0.24.0"
mmd = { git = "https://github.com/funmaker/mmd-rs" }
#mmd = { path = "../mmd-rs" }
downcast-rs = "1.2.0"
derive_deref = "1.1.1"
native-dialog = "0.5.2"
glyph_brush = "0.7.1"
unifont = "0.1.0"
nalgebra = "0.24.0"
simba = "0.3.1"
imghdr = "0.7.0"

[target.'cfg(windows)'.dependencies]
escapi = "4.0.0"
