[package]
name = "project39-ar"
version = "0.1.0"
authors = ["Fun Maker <funmaker95@gmail.com>"]
edition = "2018"

[dependencies]
vulkano = { git = "https://github.com/funmaker/vulkano", rev = "13b7188b711d7bec67bfb0267979f76b82030d5a" }
vulkano-shaders = { git = "https://github.com/funmaker/vulkano", rev = "13b7188b711d7bec67bfb0267979f76b82030d5a" }
vulkano-win = { git = "https://github.com/funmaker/vulkano", rev = "13b7188b711d7bec67bfb0267979f76b82030d5a" }
#vulkano = { path = "../vulkano/vulkano" }
#vulkano-shaders = { path = "../vulkano/vulkano-shaders" }
#vulkano-win = { path = "../vulkano/vulkano-win" }
#vulkano = "0.25.0"
#vulkano-shaders = "0.25.0"
#vulkano-win = "0.25.0"
image = "0.23.12"
openvr = "0.6.0"
openvr_sys = "2.0.3"
err-derive = "0.3.0"
getopts = "0.2.21"
arc-swap = "1.2.0"
obj-rs = "0.6.2"
opencv = { version = "0.54.0" }
num-traits = "0.2.14"
lazy_static = "1.4.0"
winit = "0.25.0"
mmd = { git = "https://github.com/funmaker/mmd-rs", rev = "9edb771b6e29da7a320acc94e8d293a4b8b0a289" }
#mmd = { path = "../mmd-rs" }
native-dialog = "0.5.2"
unifont = "0.1.0"
nalgebra = { version = "0.29.0", features = ["serde-serialize"] }
simba = "0.6.0"
imghdr = "0.7.0"
toml = "0.5.8"
serde = "1.0.126"
serde_derive = "1.0.126"
project39-ar-derive = { path = "derive" }
rapier3d = "0.11.1"

[target.'cfg(windows)'.dependencies]
escapi = "4.0.0"

[profile.dev.package.rapier3d]
opt-level = 3
