[package]
name = "project39-ar"
version = "0.1.0"
authors = ["Fun Maker <funmaker95@gmail.com>"]
edition = "2018"

[dependencies]
vulkano = "0.19.0"
vulkano-shaders = "0.19.0"
image = "0.23.12"
openvr = "0.6.0"
openvr_sys = "2.0.3"
cgmath = "0.17.0"
err-derive = "0.3.0"
getopts = "0.2.21"
arc-swap = "1.0.0"
obj-rs = "0.6.2"
opencv = { version = "0.46.3", features = ["buildtime-bindgen"] }
num-traits = "0.2.14"
num-derive = "0.3.3"
lazy_static = "1.4.0"

[target.'cfg(windows)'.dependencies]
escapi = "4.0.0"
