[package]
name = "vkeyes-demo-rs"
version = "0.1.0"
authors = ["Fun Maker <funmaker95@gmail.com>"]
edition = "2018"

[dependencies]
vulkano = "0.18.0"
vulkano-shaders = "0.18.0"
image = "0.23"
openvr = "0.6.0"
cgmath = "0.17.0"
