[package]
name = "project39-ar"
version = "0.1.0"
authors = ["Fun Maker <funmaker95@gmail.com>"]
edition = "2018"

[dependencies]
vulkano = "0.20.0"
vulkano-shaders = "0.20.0"
image = "0.23.12"
err-derive = "0.3.0"
getopts = "0.2.21"
arc-swap = "1.2.0"
obj-rs = "0.6.2"
num-traits = "0.2.14"
num-derive = "0.3.3"
lazy_static = "1.4.0"
winit = "0.24.0"
vulkano-win = "0.20.0"
mmd = { git = "https://github.com/funmaker/mmd-rs" }
#mmd = { path = "../mmd-rs" }
downcast-rs = "1.2.0"
derive_deref = "1.1.1"
native-dialog = "0.5.2"
nalgebra = "0.24.0"
simba = "0.3.1"
rand = "0.8.3"
